#-*- mode: org; mode: auto-fill -*-
#+STARTUP: showeverything
#+STARTUP: hidestars
#+TAGS: korean(k) SNU(S) CAPP(C) class(c)
#+PROPERTY: Effort_ALL 0 0:10 0:20 0:30 1:00 2:00 4:00 6:00 8:00
#DONT USE +COLUMNS: %25ITEM(Details) %TAGS(Context) %7TODO(To Do) %5Effort(Time){:} %6CLOCKSUM{Total}

* Skype Development
** TODO Loopback Video w/H264
   DEADLINE: <2011-09-30 Fri>

* Apartment
** TODO Pay the Rent
   DEADLINE: <2011-09-27 Tue ++1m -2d>

* Graphics Programming
** TODO Project 1: Robot
   DEADLINE: <2011-09-29 Thu -1d>

* Korean Study
** TODO Vocabulary Review
   SCHEDULED: <2011-09-23 Fri ++1d>
   Use Anki on my phone to review the words and phrases that are due
   today.

** TODO Study TOPIK Book
   SCHEDULED: <2011-09-23 Fri ++3d>
   Try to read passages from the TOPIK book, understand them, and input
   new vocabulary into Anki for memorization.

* VLSI Seminar						     :SNU:CAPP:class:
** TODO My Adaboost HW Presentation
   DEADLINE: <2011-09-27 Tue -2d>
   CLOCK: [2011-09-23 Fri 03:14]--[2011-09-23 Fri 04:02] =>  0:48
*** Overview
    We are working in org-mode with LaTeX babel in order to create a
    cool and pretty presentation with minimal, manual LaTeX effort.
    This should also be an awesome way to learn both org-mode, and a
    little bit of *important* LaTeX, so that I can use the same setup
    later for more important things (like writing my thesis).

