#+LATEX_CLASS: article
#+LATEX_HEADER: \usepackage{setspace}
#+LATEX_HEADER: \doublespacing
#+TITLE: Star Wars Episode 7: The Fuck? Reaction
#+AUTHOR: assEm

* Introduction
There are no adequate words that can begin to describe the emptiness
and sorrow that swelled in my heart as I left the theater after the
showing of the highly anticipated SWVII.  I had shown Jedi-like
discipline and control in waiting until Christmas day to see the
movie, avoiding Internet news and forums for the previous week in
order to avoid potential spoilers.  Perhaps this effort contributed
to increased expectations and all-the-more of a let-down.

This feeling was not just the result of the obvious - the untimely and
uncharacteristic death of a beloved hero - but because of a series of
misgivings?! that started from minute one ...

After some brief reflection on the two hour tragedy by JJ, my inner
Sith was most interested to see the flaming and flaying of the latest
installment by my expert and witty Internet brothers.  Like many
others, I expected, they would have grave misgivings with ths movie,
and possibly difficulties verbalizing them.  It was a chance to
perhaps to seek collaborative enlightenment - at the very least
achieve some small amount of healing or solace in the fact I was not
alone.

The emptiness and sorrow quickly turned to fear and to anger as I
looked at positive review after positive review that littered the
popular movie review websites.  Some of them so outrageous that I
wondered if these people had watched the same movie, or, entertaining
some great conspiracy theory, if perhaps Disney had paid armies of
both professional and amateur reviewers filling these sites.

I knew I was not completely alone however, as my girlfriend, whom had
just recently been indoctrinated into the StarWars universe (and had
actually been excited to watch each next installment), turned to me as
the credits began to roll remarking, "the original series was
better."  These were the only words of comfort I had in the moments
after, but they weren't enough to stop the bleeding of the wounds
Disney had just inflicted.

So now let's take a step back, and begin the painful process of
documenting the failures of the so-called sequel to our favorite
space soap opera.

* Redeeming Points
There were none save for one moment in the entire movie that had a
fleeting moment of Star Wars nostalgia?! for myself.  The scene where
BB8 gives a thumbs-up through creative use of a long extension arm
with a lighter.  This, mind you, was the only moment I felt like I
might be watching a Star Wars movie during the entire two hour plus
nightmare.

* The Opening Crawl
You'll never find a more wretched hive of English and literature-ee!

Seriously, I started squirming in my chair as I read through a crawl
which appeared to have been written by a five year old, English as a
second language student who had homework to finish before the next
period.  Whoever wrote the crawl probably isn't solely to blame, as it
has to introduce the upcoming story - which as we all know was
horrible.

In the months of hype before the movie was released, I had had
concerns and tried to dismiss uncomfortable ideas that the sequel
might be less than spectactular.  From this moment, however, I
immediately felt a great disturbance in the Force, and knew that I
should have walked out right then and there.

* A Sorry Excuse for a Stormtrooper
I'll disclaimer here that these first two are perhaps what my weakest
points, knowing there are others out there who might disagree.  

In the StarWars universe we've never been asked to care one shit!!
about a Stormtrooper.  They are more plot devices than people, and
while it may seem like an opportunity for an interesting new
perspective, it came off as completely uninteresting and forced.

Perhaps some writer was inspired by the recent surge of government
leaks and scandals, thinking it would be a relevant topic for
present-day by embodying this in the visage of a troubled young
Stormtrooper.  Or perhaps, and more likely, it was just a convenient
way to advance the plot by having the master key walking alongside
you.

* Diversity By Disney
The accents, skin colors, and genders portrayed in the movie are a
veritable cornucopia of diversity, as if to be sure they hadn't left
anyone out.  Unfortunately, people aren't as weak-minded as you might
think and see through you, we do.  Your thoughts revolve around
diversity?!

* There's No Blood in StarWars!
In the opening scene of the movie, a wounded Stormtrooper reaches out
to his comrade for help, inadvertantly?! smearing blood across the
otherwise white helmet.  There was an immediate, internal knee-jerk
reaction to this, as StarWars has never been one to show blood or gore
for the purpose of shock value.  The only moment in the previous
series where I can recall blood being shown was from the EpII from the
grasshopper/mantis like monster (green?!) and in EpV the monster on
Endor that lost his hand after he knabbed Luke.  In both of these
cases however, it was almost unnoticeable and definitely not to be
the center of attention of the moment.

* Welcome to Tattoi...I mean Jakku!
Are you joking? Another desert island-type planet that appears to
have been a battleground of some sort so that scavengers now roam and
sell parts for food rations...

Anakin and his mother were slaves, but the visual depiction of the
harsh and brutal reality of slavery was largely avoided in the
original movies.  It was cleverly implanted (and quickly too) and
since everyone knows that slavery is bad, it was easy to accept that
we needed to cheer for Anakin and that Watto was something of a
villian.

In episode VII however, we are forced to suffer through the harsh
reality of our would-be hero, Rey, as she desperately struggles to put
food on the table.  The trouble is that the process is somewhat
uninteresting and feels like filler that should have been alloted for
more interesting character dialogue (oh wait, there was almost none
of that!).

* Millenium Falcon on Jakku?!
Does it seem reasonable that the Millenium Falcon would be away from
our hero Han Solo and on Jakku long enough for it to become a pile of
junk that can't start (well maybe it was already junk 30 years earlier)?

Does it seem reasonable that Han Solo would let it happen in the
first place?  Perhaps, you say, and I might agree if we had more to
go on than 
